default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
        exclude: \.vscode
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.1"
    hooks:
      # backends/fastapi
      - name: ruff-check-backend-fastapi
        files: ^backends/fastapi/
        id: ruff-check
        args: [--fix]
        types_or: [python, pyi, jupyter]

      - name: ruff-format-backend-fastapi
        files: ^backends/fastapi/
        id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.10.4"
    hooks:
      # backends/fastapi
      - name: uv-lock-backend-fastapi
        files: ^backends/fastapi/
        id: uv-lock
        entry: pre-commit hazmat cd backends/fastapi uv lock --
        args: []

      - name: uv-sync-backend-fastapi
        files: ^backends/fastapi/
        id: uv-sync
        entry: pre-commit hazmat cd backends/fastapi uv sync --locked --all-groups --
        args: []
  - repo: local
    hooks:
      - id: ty
        name: ty-check-fastapi
        entry: pre-commit hazmat cd backends/fastapi uv run ty check . --python .venv --
        pass_filenames: false
        always_run: true
        language: system
        args: []
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.8.1"
    hooks:
      - id: prettier
        types_or: [json, yaml]
