# Docker compose specification for all apps to start up.

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on:
      - backend-fastapi
      - frontend-nextjs
    develop:
      watch:
        - action: rebuild
          path: ./nginx/nginx.conf

  frontend-nextjs:
    # Tilt makes the build for us.
    image: frontend-nextjs
    # If using Docker Compose alone, comment the above,
    # then uncomment below:
    # container_name: frontend-nextjs
    # build:
    #   context: ./frontends/nextjs
    #   dockerfile: Dockerfile
    # restart: always

  backend-fastapi:
    # Tilt makes the build for us.
    image: backend-fastapi
    # If using Docker Compose alone, comment the above,
    # then uncomment below:
    # container_name: backend-fastapi
    # build:
    #   context: ./backends/fastapi
    #   dockerfile: Dockerfile
    env_file:
      - ./backends/fastapi/.env
    restart: always
