## Run the CI suite in PRs and on pushes to the main branch.

name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      # Defaults
      - opened
      - synchronize
      - reopened
      # Draft->ready
      - ready_for_review
      # Edit the title or top comment
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    # Elevating permissions for `contents` and `pull-requests` required
    # when using the `suggest_fixes` option:
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: griceturrble/precommit-checks-action@v3
        with:
          suggest_fixes: true

  test-backends:
    if: ${{ !github.event.pull_request || !contains(github.event.pull_request.title, '[draft]') }}
    name: Test backend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - fastapi
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Install just runner
        uses: extractions/setup-just@v3

      # TODO replace this with some backend-specific call to install its tools?
      # I don't know how feasible that is, but worth a shot
      - name: Install uv
        if: ${{ contains('fastapi', matrix.backend) }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

      - name: Install project dependencies
        working-directory: ./backends/${{ matrix.backend }}
        run: just sync

      - name: Run tests
        working-directory: ./backends/${{ matrix.backend }}
        run: just test

  test-frontends:
    if: ${{ !github.event.pull_request || !contains(github.event.pull_request.title, '[draft]') }}
    name: Test frontend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        frontend:
          - nextjs
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Install just runner
        uses: extractions/setup-just@v3

      - name: Setup Node
        if: ${{ contains('nextjs', matrix.frontend) }}
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./frontends/${{ matrix.frontend }}/package-lock.json

      - name: Install project dependencies
        working-directory: ./frontends/${{ matrix.frontend }}
        run: just sync

      - name: Run tests
        working-directory: ./frontends/${{ matrix.frontend }}
        run: just test

  test-result:
    if: ${{ !github.event.pull_request || !contains(github.event.pull_request.title, '[draft]') }}
    name: Test results
    runs-on: ubuntu-latest
    needs:
      - test-backends
      - test-frontends
    steps:
      - run: echo "Tests passing!"
