## Run the CI suite in PRs and on pushes to the main branch.

name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      # Defaults
      - opened
      - synchronize
      - reopened
      # Draft->ready
      - ready_for_review
      # Edit the title or top comment
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    # Elevating permissions for `contents` and `pull-requests` required
    # when using the `suggest_fixes` option:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ !github.event.pull_request || !contains(github.event.pull_request.title, '[draft]') }}
    steps:
      - uses: actions/checkout@v6
      - uses: griceturrble/precommit-checks-action@v3
        with:
          suggest_fixes: true

  test-backend-fastapi:
    name: Tests - Python FastAPI backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      # TODO replace with the setup-just task (likely faster, not a big deal here)
      # Or, just use the native commands? Skip the thing?
      - name: Install just runner
        uses: extractions/setup-just@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

      - name: Install project dependencies
        working-directory: ./backends/fastapi
        run: just sync

      - name: Run tests
        working-directory: ./backends/fastapi
        run: just test

  test-result:
    name: Test results
    runs-on: ubuntu-latest
    needs:
      - test-backend-fastapi
    steps:
      - run: echo "Tests passing!"
